---
- name: Install Nginx
  hosts: all
  # remote_user: root
  sudo: yes

  tasks:
    - name: update apt cache
      apt: update_cache=yes

  roles:
    # - common
    - angstwad.docker_ubuntu #ansible-galaxy install angstwad.docker_ubuntu
    - nginx
    - golang
